AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB Tables for Siftbeam Application - Refactored with camelCase PKs'

Resources:
  # ==========================================
  # Announcements Table
  # ==========================================
  AnnouncementsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: siftbeam-announcements
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: announcementId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: announcementId
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE
      Tags:
        - Key: Application
          Value: Siftbeam
        - Key: Environment
          Value: Production

  # ==========================================
  # API Keys Table
  # ==========================================
  ApiKeysTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: siftbeam-api-keys
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: apiKeyId
          AttributeType: S
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: apiKeyId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: customerId-createdAt-index
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Application
          Value: Siftbeam

  # ==========================================
  # Audit Logs Table
  # ==========================================
  AuditLogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: siftbeam-audit-logs
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: auditLogId
          AttributeType: S
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: auditLogId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: customerId-createdAt-index
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Application
          Value: Siftbeam

  # ==========================================
  # Data Usage Table
  # ==========================================
  DataUsagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: siftbeam-data-usages
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: dataUsageId
          AttributeType: S
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: dataUsageId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: customerId-createdAt-index
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: userId-createdAt-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Application
          Value: Siftbeam

  # ==========================================
  # Groups Table
  # ==========================================
  GroupsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: siftbeam-groups
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: groupId
          AttributeType: S
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: groupName
          AttributeType: S
      KeySchema:
        - AttributeName: groupId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: customerId-createdAt-index
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: customerId-groupName-index
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
            - AttributeName: groupName
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Application
          Value: Siftbeam

  # ==========================================
  # New Order Replies Table
  # ==========================================
  NewOrderRepliesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: siftbeam-new-order-replies
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: newOrderReplyId
          AttributeType: S
        - AttributeName: newOrderRequestId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: newOrderReplyId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: newOrderRequestId-createdAt-index
          KeySchema:
            - AttributeName: newOrderRequestId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Application
          Value: Siftbeam

  # ==========================================
  # New Order Requests Table
  # ==========================================
  NewOrderRequestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: siftbeam-new-order-requests
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: newOrderRequestId
          AttributeType: S
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: newOrderRequestId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: customerId-createdAt-index
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: customerId-status-index
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: status-createdAt-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Application
          Value: Siftbeam

  # ==========================================
  # Policies Table
  # ==========================================
  PoliciesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: siftbeam-policies
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: policyId
          AttributeType: S
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: policyName
          AttributeType: S
      KeySchema:
        - AttributeName: policyId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: customerId-createdAt-index
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: customerId-policyName-index
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
            - AttributeName: policyName
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Application
          Value: Siftbeam

  # ==========================================
  # Policy Analyses Table
  # ==========================================
  PolicyAnalysesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: siftbeam-policy-analyses
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: policyAnalysisId
          AttributeType: S
        - AttributeName: policyId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: policyAnalysisId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: policyId-createdAt-index
          KeySchema:
            - AttributeName: policyId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Application
          Value: Siftbeam

  # ==========================================
  # Policy Groups Table
  # ==========================================
  PolicyGroupsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: siftbeam-policy-groups
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: policyGroupId
          AttributeType: S
        - AttributeName: groupId
          AttributeType: S
        - AttributeName: policyId
          AttributeType: S
      KeySchema:
        - AttributeName: policyGroupId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: groupId-policyId-index
          KeySchema:
            - AttributeName: groupId
              KeyType: HASH
            - AttributeName: policyId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Application
          Value: Siftbeam

  # ==========================================
  # Policy Step Function Mappings Table
  # ==========================================
  PolicyStepFunctionMappingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: siftbeam-policy-step-function-mappings
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: policyId
          AttributeType: S
      KeySchema:
        - AttributeName: policyId
          KeyType: HASH
      Tags:
        - Key: Application
          Value: Siftbeam

  # ==========================================
  # Processing Histories Table
  # ==========================================
  ProcessingHistoriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: siftbeam-processing-histories
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: processingHistoryId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: processingHistoryId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: userId-createdAt-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: customerId-createdAt-index
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: customerId-status-index
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Application
          Value: Siftbeam

  # ==========================================
  # Support Replies Table
  # ==========================================
  SupportRepliesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: siftbeam-support-replies
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: supportReplyId
          AttributeType: S
        - AttributeName: supportRequestId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: supportReplyId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: supportRequestId-createdAt-index
          KeySchema:
            - AttributeName: supportRequestId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Application
          Value: Siftbeam

  # ==========================================
  # Support Requests Table
  # ==========================================
  SupportRequestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: siftbeam-support-requests
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: supportRequestId
          AttributeType: S
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: supportRequestId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: customerId-createdAt-index
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: customerId-status-index
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: status-createdAt-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Application
          Value: Siftbeam

  # ==========================================
  # Usage Limits Table
  # ==========================================
  UsageLimitsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: siftbeam-usage-limits
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: usageLimitId
          AttributeType: S
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: usageLimitId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: customerId-createdAt-index
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Application
          Value: Siftbeam

  # ==========================================
  # User Groups Table
  # ==========================================
  UserGroupsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: siftbeam-user-groups
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userGroupId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: groupId
          AttributeType: S
      KeySchema:
        - AttributeName: userGroupId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: userId-groupId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: groupId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: groupId-userId-index
          KeySchema:
            - AttributeName: groupId
              KeyType: HASH
            - AttributeName: userId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Application
          Value: Siftbeam

  # ==========================================
  # Users Table
  # ==========================================
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: siftbeam-users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: userName
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: customerId-userName-index
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
            - AttributeName: userName
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Application
          Value: Siftbeam

  # ==========================================
  # Verification Codes Table
  # ==========================================
  VerificationCodesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: siftbeam-verification-codes
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: verificationId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: verificationId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-createdAt-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Application
          Value: Siftbeam

Outputs:
  AnnouncementsTableName:
    Description: Announcements Table Name
    Value: !Ref AnnouncementsTable
    Export:
      Name: !Sub '${AWS::StackName}-AnnouncementsTable'

  ApiKeysTableName:
    Description: API Keys Table Name
    Value: !Ref ApiKeysTable
    Export:
      Name: !Sub '${AWS::StackName}-ApiKeysTable'

  AuditLogsTableName:
    Description: Audit Logs Table Name
    Value: !Ref AuditLogsTable
    Export:
      Name: !Sub '${AWS::StackName}-AuditLogsTable'

  UsersTableName:
    Description: Users Table Name
    Value: !Ref UsersTable
    Export:
      Name: !Sub '${AWS::StackName}-UsersTable'

